# Backend app (api). Defines the backend application with some defaults (php + redis + mysql extensions)
FROM php:8.1.2-fpm-alpine

RUN apk update && apk add --update \
    libtool \
    g++ \
    autoconf \
    make \
    zlib-dev \
    libzip-dev \
    oniguruma-dev \
    && pecl install redis-5.3.6 \
    && docker-php-ext-install mbstring pdo_mysql iconv zip opcache \
    && docker-php-ext-enable redis \
    && apk del autoconf g++ libtool make \
    && rm -rf /tmp/* /var/cache/apk/* /usr/src/* /code

WORKDIR /code
