# Nginx webserver. Proxies incoming requests to the backend app (api).
FROM nginx:latest

# Make sure we start with no configuration files, since we want to use our own, and only our own
# This prevents other config from interfering with the one we inject
RUN rm -rf /etc/nginx/nginx.conf && rm -rf /etc/nginx/conf.d/default.conf

# Install our configuration file on the default webserver location
COPY ./nginx.conf /etc/nginx/nginx.conf

